#!/bin/bash

export LC_ALL="$LANG"
export LC_TIME="en_GB.UTF-8"
export LC_PAPER="en_GB.UTF-8"
export LC_MEASUREMENT="en_GB.UTF-8"

export PIPENV_MAX_DEPTH=10

alias gitsu='git submodule update -i --recursive'
alias gti='git'
alias gck='git checkout'
alias gst='git status'
alias gsu='gitsu'
alias g="git"

alias gitupm="gitup master"

alias tmux-env="tmux show-environment"

alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

if command -v __git_ps1 &>/dev/null; then
    alias _bashrc_git_ps1=__git_ps1
else
    alias _bashrc_git_ps1=true
fi

export GIT_PS1_SHOWSTASHSTATE=1
export PS1='\[\e[34;1m\]\u@'\
'\[\e[32;1m\]\H:'\
'$(ret=$?; if [ $ret -ne 0 ]; then echo " \[\e[31;7m\]"$ret"\[\e[0m\]"; fi)'\
'\[\e[31;1m\]$(_bashrc_git_ps1) '\
'\[\e[0m\]\w'\
'\[\e[31;1m\]\$ '\
'\[\e[0m\]'

if ! command -v pbcopy &>/dev/null; then
    alias pbcopy='xclip -selection clipboard'
fi

if ! command -v pbpaste &>/dev/null; then
    alias pbpaste='xclip -selection clipboard -o'
fi

function psax {
    ps ax | grep --color=always "$@" | grep -v grep
}

function tmux-re {
    local v
    while read v; do
        if [[ $v == -* ]]; then
            unset ${v/#-/}
        else
            # Add quotes around the argument
            v=${v/=/=\"}
            v=${v/%/\"}
            eval export $v
        fi
    done < <(tmux show-environment)
}

function randbug {
    local i=1;
    while "$@"; do
        echo "---------- randbug: run #$i done ----------";
        i=$((i+1));
    done
    echo "randbug: failure occurred at run #$i";
}

function build-nenv {
    NO_DOUBLE_FPIC=1 NOCHECK=1 NO_JAVA=1 NOCOMPRESS=1 FAKE_VERSIONS=1 "$@"
}

function build-noweb-env {
    NO_WWW=1 "$@"
}

function build-no-www-check-env {
    NO_WWW_CHECK=1 "$@"
}

function build-www-dev {
    WWW_DEV=1 "$@"
}

function build-denv {
    P=debug "$@"
}

function build-renv {
    P=release "$@"
}

function build-aenv {
    P=asan "$@"
}

function no-stderr {
    "$@" 2>/dev/null
}

function waf-configure {
    # waf configure with fast environment variables
    # Always execute waf at the root of the repository
    local exit_code

    pushd "$(git rev-parse --show-toplevel)" || return 1
    waf configure "$@"
    exit_code=$?
    popd || return 1

    return $exit_code
}

alias wafc='waf-configure'
alias wafcn='build-nenv waf-configure'
alias wafcdn='build-denv build-nenv waf-configure'
alias wafcrn='build-renv build-nenv waf-configure'
alias wafcan='build-aenv build-nenv waf-configure'
alias wafcd='build-denv waf-configure'
alias wafcr='build-renv waf-configure'
alias wafca='build-aenv waf-configure'

alias baf='build-noweb-env waf'
alias bafs='no-stderr build-noweb-env waf'
alias wafs='no-stderr waf'
alias wwaf='build-no-www-check-env waf'
alias wdwaf='build-www-dev waf'
alias wwdwaf='build-no-www-check-env build-www-dev waf'

alias maken='build-nenv make'
alias makedn='build-denv build-nenv make'
alias makern='build-renv build-nenv make'
alias makean='build-aenv build-nenv make'
alias maked='build-denv make'
alias maker='build-renv make'
alias makea='build-aenv make'

alias makes='no-stderr make'
alias makens='no-stderr build-nenv make'
alias makedns='no-stderr build-denv build-nenv make'
alias makerns='no-stderr build-renv build-nenv make'
alias makeans='no-stderr build-aenv build-nenv make'
alias makeds='no-stderr build-denv make'
alias makers='no-stderr build-renv make'
alias makeas='no-stderr build-aenv make'
