#!/bin/bash

export LC_ALL="$LANG"
export LC_TIME="en_GB.UTF-8"
export LC_PAPER="en_GB.UTF-8"
export LC_MEASUREMENT="en_GB.UTF-8"

alias gitsu='git submodule update -i --recursive'
alias gti='git'
alias gck='git checkout'
alias gst='git status'
alias gsu='gitsu'
alias g="git"

alias gitupm="gitup master"

alias tmux-env="tmux show-environment"

if ! which pbcopy >/dev/null; then
    alias pbcopy='xclip -selection clipboard'
fi

if ! which pbpaste >/dev/null; then
    alias pbpaste='xclip -selection clipboard -o'
fi

function psax {
    ps ax | grep --color=always $* | grep -v grep
}

function tmux-re {
    local v
    while read v; do
        if [[ $v == -* ]]; then
            unset ${v/#-/}
        else
            # Add quotes around the argument
            v=${v/=/=\"}
            v=${v/%/\"}
            eval export $v
        fi
    done < <(tmux show-environment)
}

function build-nenv {
    NOCHECK=1 NO_JAVA=1 NO_DOUBLE_FPIC=1 NOCOMPRESS=1 $@
}

function build-noweb-env {
    NO_WWW=1 $@
}

function build-denv {
    P=debug $@
}

function build-renv {
    P=release $@
}

function build-aenv {
    P=asan $@
}

function no-stderr {
    $@ 2>/dev/null
}

function waf-build {
    (cd $(git rev-parse --show-toplevel) && waf configure) && waf $@
}

alias wafn='build-nenv waf-build'
alias wafdn='build-denv build-nenv waf-build'
alias wafrn='build-renv build-nenv waf-build'
alias wafan='build-aenv build-nenv waf-build'
alias wafd='build-denv waf-build'
alias wafr='build-renv waf-build'
alias wafa='build-aenv waf-build'

alias wafs='no-stderr waf-build'
alias wafns='no-stderr build-nenv waf-build'
alias wafdns='no-stderr build-denv build-nenv waf-build'
alias wafrns='no-stderr build-renv build-nenv waf-build'
alias wafans='no-stderr build-aenv build-nenv waf-build'
alias wafds='no-stderr build-denv waf-build'
alias wafrs='no-stderr build-renv waf-build'
alias wafas='no-stderr build-aenv waf-build'

alias wafc='build-noweb-env waf-build'
alias wafcn='build-noweb-env build-nenv waf-build'
alias wafcdn='build-noweb-env build-denv build-nenv waf-build'
alias wafcrn='build-noweb-env build-renv build-nenv waf-build'
alias wafcan='build-noweb-env build-aenv build-nenv waf-build'
alias wafcd='build-noweb-env build-denv waf-build'
alias wafcr='build-noweb-env build-renv waf-build'
alias wafca='build-noweb-env build-aenv waf-build'

alias wafcs='no-stderr build-noweb-env waf-build'
alias wafcns='no-stderr build-noweb-env build-nenv waf-build'
alias wafcdns='no-stderr build-noweb-env build-denv build-nenv waf-build'
alias wafcrns='no-stderr build-noweb-env build-renv build-nenv waf-build'
alias wafcans='no-stderr build-noweb-env build-aenv build-nenv waf-build'
alias wafcds='no-stderr build-noweb-env build-denv waf-build'
alias wafcrs='no-stderr build-noweb-env build-renv waf-build'
alias wafcas='no-stderr build-noweb-env build-aenv waf-build'

alias maken='build-nenv make'
alias makedn='build-denv build-nenv make'
alias makern='build-renv build-nenv make'
alias makean='build-aenv build-nenv make'
alias maked='build-denv make'
alias maker='build-renv make'
alias makea='build-aenv make'

alias makes='no-stderr make'
alias makens='no-stderr build-nenv make'
alias makedns='no-stderr build-denv build-nenv make'
alias makerns='no-stderr build-renv build-nenv make'
alias makeans='no-stderr build-aenv build-nenv make'
alias makeds='no-stderr build-denv make'
alias makers='no-stderr build-renv make'
alias makeas='no-stderr build-aenv make'
