#!/bin/sh -eu

# shellcheck disable=SC2155

if [ "$#" -lt 2 ]; then
    echo "usage: $0 Z_WWW_PREFIX [Chrome] cmd [args...]"
    exit 1
fi

export Z_WWW_HOST="localhost"
export Z_WWW_PREFIX=$1
shift

if [ "$1" = "Chrome" ]; then
    export Z_WWW_BROWSER="Chrome"
    shift
else
    export Z_WWW_BROWSER="Firefox"
    export Z_WWW_BIN_PATH="/home/pauss/opt/firefox/firefox"
fi

params=""
for param in "$@"
do
  params="${params} \"${param}\""
done
eval "$params"
