#!/usr/bin/env python

from kazoo.client import KazooClient
from os import path as osp

path = osp.expandvars('/~${USER}/one-${HOSTNAME}')

zk = KazooClient(hosts='zk.corp')
zk.start()
zk.delete(path, recursive=True)
zk.ensure_path(path)
zk.stop()

