#!/bin/sh -eu

clean_args="${1:--ffXdd}"

cd "$(git rev-parse --show-toplevel)"
if ! git clean "$clean_args"; then
    sudo git clean "$clean_args"
fi
if ! git submodule foreach git clean "$clean_args"; then
    sudo git submodule foreach git clean "$clean_args"
fi
