#!/bin/sh -eu

cd "$(git rev-parse --show-toplevel)"
if ! git clean -ffxxd; then
    sudo git clean -ffxxd
fi
if ! git submodule foreach git clean -ffxxd; then
    sudo git submodule foreach git clean -ffxxd
fi
