#!/bin/bash -eu

main() {
    local pl_arg="$1"
    local pl_arg_arr
    local pl_process
    local pl_sock_prefix

    shift

    readarray -d '/' -t pl_arg_arr <<< "$pl_arg"
    pl_process="$(tr -d '\n' <<< "${pl_arg_arr[0]:-}")"
    pl_sock_prefix="$(tr -d '\n' <<< "${pl_arg_arr[1]:-}")"
    pl_service_name="$(tr -d '\n' <<< "${pl_arg_arr[2]:-}")"

    # shellcheck disable=SC2155
    export PLATFORM_MASTER_PID="$(pidof "$pl_process-master")"
    export PLATFORM_BINDIR="$PWD"
    export PLATFORM_PREFIX="$PWD/prefix"
    export PLATFORM_HOST_IP="127.0.0.1"
    export PLATFORM_CTLSOCK="@/var/run/$pl_process$pl_sock_prefix-master.ctl"
    if [ -n "$pl_service_name" ]; then
        export PLATFORM_SERVICE_NAME="$pl_service_name"
    fi
    exec "$@"
}

main "$@"
